version: '3'

services:

  web:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - application
    networks:
      - test_network

  database:
    container_name: mysql_db
    restart: always
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ssafy
      TZ: 'Asia/Seoul'
    ports:
      - "3307:3307"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - test_network

  application:
    container_name: docker-compose-test
    build:
      context: ./
      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
    expose:
      - 8080
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/users_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
#      SPRING_DATASOURCE_USERNAME: "root"
#      SPRING_DATASOURCE_PASSWORD: "1234"
    depends_on:
      - database
    networks:
      - test_network

networks:
  test_network: